/**
 * ABI sync: copies the `abi` field from Hardhat artifacts into the frontend
 * (`pkgs/frontend/abi/*.ts`) and the subgraph (`pkgs/subgraph/abis/*.json`).
 *
 * Hand-maintained copies drift; the BigBang/HatsQuestModule sync commit
 * b1fb240 and the ScheduledDistributorFactory `backupWallet` event mismatch
 * were both this exact issue. Run after every contract compile:
 *
 *   pnpm contract compile && pnpm contract sync:abis
 *
 * Wired as `sync:abis` in pkgs/contract/package.json.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const REPO_ROOT = resolve(__dirname, "../../../..");
const ARTIFACTS = resolve(REPO_ROOT, "pkgs/contract/artifacts/contracts");
const FRONTEND_ABI_DIR = resolve(REPO_ROOT, "pkgs/frontend/abi");
const SUBGRAPH_ABI_DIR = resolve(REPO_ROOT, "pkgs/subgraph/abis");

type FrontendTarget = {
  file: string;
  /** Map of `export const NAME = ...` → artifact path (relative to ARTIFACTS). */
  exports: { name: string; artifact: string }[];
};

const FRONTEND_TARGETS: FrontendTarget[] = [
  {
    file: "bigbang.ts",
    exports: [
      { name: "BIGBANG_ABI", artifact: "bigbang/BigBang.sol/BigBang.json" },
    ],
  },
  {
    file: "fractiontoken.ts",
    exports: [
      {
        name: "FRACTION_TOKEN_ABI",
        artifact:
          "hatsmodules/fractiontoken/HatsFractionTokenModule.sol/HatsFractionTokenModule.json",
      },
    ],
  },
  {
    file: "hats.ts",
    exports: [{ name: "HATS_ABI", artifact: "hats/src/Hats.sol/Hats.json" }],
  },
  {
    file: "hatsHatCreatorModule.ts",
    exports: [
      {
        name: "HATS_HAT_CREATOR_MODULE_ABI",
        artifact:
          "hatsmodules/hatcreator/HatsHatCreatorModule.sol/HatsHatCreatorModule.json",
      },
    ],
  },
  {
    file: "hatsQuestModule.ts",
    exports: [
      {
        name: "HATS_QUEST_MODULE_ABI",
        artifact: "hatsmodules/quest/HatsQuestModule.sol/HatsQuestModule.json",
      },
    ],
  },
  {
    file: "hatsTimeFrameModule.ts",
    exports: [
      {
        name: "HATS_TIME_FRAME_MODULE_ABI",
        artifact:
          "hatsmodules/timeframe/HatsTimeFrameModule.sol/HatsTimeFrameModule.json",
      },
    ],
  },
  {
    file: "scheduledDistributor.ts",
    exports: [
      {
        name: "SCHEDULED_DISTRIBUTOR_ABI",
        artifact:
          "scheduleddistributor/ScheduledDistributor.sol/ScheduledDistributor.json",
      },
      {
        name: "SCHEDULED_DISTRIBUTOR_FACTORY_ABI",
        artifact:
          "scheduleddistributor/ScheduledDistributorFactory.sol/ScheduledDistributorFactory.json",
      },
    ],
  },
  {
    file: "splits.ts",
    exports: [
      {
        name: "SPLITS_CREATOR_ABI",
        artifact: "splitscreator/SplitsCreator.sol/SplitsCreator.json",
      },
    ],
  },
  {
    file: "thankstoken.ts",
    exports: [
      {
        name: "THANKS_TOKEN_ABI",
        artifact: "thankstoken/ThanksToken.sol/ThanksToken.json",
      },
    ],
  },
];

const SUBGRAPH_TARGETS: { file: string; artifact: string }[] = [
  { file: "BigBang.json", artifact: "bigbang/BigBang.sol/BigBang.json" },
  {
    file: "HatsQuestModule.json",
    artifact: "hatsmodules/quest/HatsQuestModule.sol/HatsQuestModule.json",
  },
  {
    file: "ScheduledDistributor.json",
    artifact:
      "scheduleddistributor/ScheduledDistributor.sol/ScheduledDistributor.json",
  },
  {
    file: "ScheduledDistributorFactory.json",
    artifact:
      "scheduleddistributor/ScheduledDistributorFactory.sol/ScheduledDistributorFactory.json",
  },
];

function loadAbi(artifactPath: string): unknown[] {
  const full = resolve(ARTIFACTS, artifactPath);
  const json = JSON.parse(readFileSync(full, "utf8"));
  if (!Array.isArray(json.abi)) {
    throw new Error(`No abi[] in ${full}`);
  }
  return json.abi;
}

function syncFrontend() {
  for (const target of FRONTEND_TARGETS) {
    const blocks = target.exports.map(({ name, artifact }) => {
      const abi = loadAbi(artifact);
      return `export const ${name} = ${JSON.stringify(abi, null, 2)} as const;`;
    });
    const banner =
      "// AUTO-GENERATED by scripts/utils/syncAbis.ts — do not edit by hand.\n// Source: pkgs/contract/artifacts/contracts/...\n\n";
    const body = `${banner}${blocks.join("\n\n")}\n`;
    const out = resolve(FRONTEND_ABI_DIR, target.file);
    writeFileSync(out, body);
    console.log(`frontend  ${target.file}`);
  }
}

function syncSubgraph() {
  for (const target of SUBGRAPH_TARGETS) {
    const abi = loadAbi(target.artifact);
    const out = resolve(SUBGRAPH_ABI_DIR, target.file);
    writeFileSync(out, `${JSON.stringify(abi, null, 2)}\n`);
    console.log(`subgraph  ${target.file}`);
  }
}

syncFrontend();
syncSubgraph();
