name: Deploy document to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  # build job
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.4

      - name: Install dependencies
        run: pnpm install

      - name: Build Document
        run: pnpm document build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pkgs/document/build
  # deploy job
  deploy:
    name: Deploy to GitHub Pages
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Document
        id: deployment
        uses: actions/deploy-pages@v4

concurrency:
  group: "pages"
  cancel-in-progress: false
